### ISSUE TITLE
Mau Cari Apa Tod...

### ISSUE THREAD

**Issue by MrTamfanX** [MrUncle/Script-Hack-Bank#1]
Masukkan Perintah 
Hack Pulsa Gratis Via Termux
$apt update && apt upgrade
$apt install php
$apt install toilet
$apt install git
$git clone https://github.com/MrUncle/PulsaGratis
$cd PulsaGratis
$ls
$chmod +x *
$ls
$sh Pulsa.sh

Hack Bank By MrTamfanX
$apt update && apt upgrade
$apt install php
$apt install git
$git clone https://github.com/MrUncle/Script-HackBank
$cd Script-HackBank
$ls
$chmod +x *
$ls
$sh ALLBANK

**Comment by Andipandip** [comment]
Not work.. Pembodohan publik

**Comment by donidamara12** [comment]
Bnr itu
